### ISSUE TITLE
Kalman mode warning; potential solution...

### ISSUE THREAD

**Issue by Nuihc88** [pinterf/FFT3dGPU#2]
![Kalman_X3576](https://user-images.githubusercontent.com/58824736/79811490-a5dc0800-837e-11ea-9531-e4fcfc6cec64.png)
After encountering this error while trying out 'bt=0', i had a look at the HLSL source and figured out that it's possible to get rid of this error by removing `:COLOR` part of this line:
`PS_RETVAL Kalman(PS_INPUT In):COLOR`
...as it would appear to just be unnecessarily overriding this struct:
```
struct PS_RETVAL
{
	float4 dst : COLOR0;
	float4 covar :COLOR1;
	float4 covarprocess :COLOR2;
};
```
That said, i could be missing something as i'm relatively new to HLSL and haven't checked if or how it might change the output and if that's for better or worse.

**Comment by pinterf** [comment]
Thanks, I don't have time now for that but don't forget to ping me later on this. Since I have to build new versions for all my plugins after the next avs+ release for support a new feature, hopefully I'll remember this.

**Comment by Nuihc88** [comment]
Ok, i noticed that you started to build new plugin versions after releasing the r3218 test build, so here's the reminder you asked for...

**Comment by pinterf** [comment]
Yep, I found a similar one, 
https://gamedev.stackexchange.com/questions/81712/hlsl-pixel-shader-sematics
Seems to be really unnecessary but I cannot tell you 100%

**Comment by pinterf** [comment]
Finally... there was a good other reason for the release, so this one is incorporated as well. Thanks.
