### ISSUE TITLE
Error when use with avisynth plus 3.6.2 test 2b

### ISSUE THREAD

**Issue by kedaitinh12** [pinterf/FFT3dGPU#3]
I meet error: "access violation" when use with avs+ 3.6.2 test 2b

And you can update FFT3dGPU with more than 8 bit???

**Comment by pinterf** [comment]
Script please, as minimal as possible that still exhibits the behaviour.

**Comment by kedaitinh12** [comment]
I used with temporaldegrain2

Script:
TemporalDegrain2(postFFT=2)

**Comment by pinterf** [comment]
Could not reproduce.

Have you put fft3dgpu.hlsl next to the DLL?

In general, I expect a "bit" more help. This is not a proper issue report.

Which temporaldegrain2 version
Color space, dimensions of the clip, or provide the clip itself (a shortened one of course)
x86 or x64?
Did it work with earlier Avisynth versions versions?

I was trying with this script.
```
Import("TemporalDegrain-v2.2.1.avsi")
Colorbars()
ConvertToYV12()
TemporalDegrain2(postFFT=2)
```

p.s.
If possible do not mix a feature request with a specific bug report when you start an Issue

**Comment by kedaitinh12** [comment]
> Have you put fft3dgpu.hlsl next to the DLL?

oh, i forgot it. Sr about my mistake and i will split feature request and specific bug report
